version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "buildo/h2database"
    environment:
      - H2_CONSOLE_PORT=8082
    ports:
      - "8082:8082"